name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build with Buildozer
        # आपण आता डायरेक्ट डोकॅर इमेज वापरू जी कधीच फेल होणार नाही
        uses: docker://kivy/buildozer:latest
        with:
          args: android debug

      - name: Upload APK
        # इथे आपण नवीन v4 वापरतोय जो आताचा लेटेस्ट आहे
        uses: actions/upload-artifact@v4
        with:
          name: Friday-App-Package
          path: bin/*.apk
